### PR TITLE
Change NodeID

### PR DESCRIPTION
**Pull request by prestoncraw**

### CODE REVIEW

**Comment by StephenCWills** [comment]
Is there something wrong with the current node ID? And why are we making one up instead of simply generating a new one?

FYI, there's a standard the specifies the format of a GUID, and this one seems to fall under the "legacy Apollo NCS UUID" format. We usually just generate a version-4 GUID. Because it's randomly generated, it's easy to make new ones. In Visual Studio, go to `Tools > Create GUID`.

**Comment by prestoncraw** [comment]
The current node ID in `Web.config` was from the commit below so I figured we didnt want local node IDs in the Web.config https://github.com/GridProtectionAlliance/SEBrowser/commit/fc95088c40357489ed1e40e0733f93fdfeefdb9b#diff-2ef2308f0d14a5fef53a74064dc980999b4c78ac2e13a035c6ebb279a84b9400`

I set up a `Secret-Check` pipeline to check `Web.config` for secrets and I assumed a generic 1234...etc would be fine for an example node ID.

**Comment by StephenCWills** [comment]
It goes back before that, actually: https://github.com/GridProtectionAlliance/SEBrowser/commit/a3ce2c82b599af2b69a453ca9f5c930374ec1c23#diff-2ef2308f0d14a5fef53a74064dc980999b4c78ac2e13a035c6ebb279a84b9400

The previous value was `00000000-0000-0000-0000-000000000000`, which is the "default" or "null" GUID. openXDA was using that one because it didn't originally have the `ApplicationNode` table, but the security code still needed the `NodeID` parameter in the config file. We can either go back to using that, or we can generate a new one, or we can continue using the same value we use internally. It was randomly generated, and it isn't really a secret as it's only used to differentiate different instances of the applications.

**Comment by clackner-gpa** [comment]
I am aware it does technically not constitute a secret, but I figured we don't want the NodeID to change constantly either so the PipeLine should not allow replacements. Any objections if we just use the one in the Demo System?

**Review by clackner-gpa — APPROVED** [review]

**Review by StephenCWills — APPROVED** [review]

**Pull request merged**
